import { readdir, stat } from 'fs/promises';
import { join, relative, extname, dirname } from 'path';
import type { Plugin } from 'vite';

interface ThumbnailRegistryOptions {
	assetsDir: string;
	outputFile: string;
	imageExtensions: string[];
}

const defaultOptions: ThumbnailRegistryOptions = {
	assetsDir: 'src/lib/assets',
	outputFile: 'src/lib/articles/generated-thumbnails.ts',
	imageExtensions: ['.png', '.jpg', '.jpeg', '.webp', '.avif', '.svg']
};

/**
 * Vite plugin that automatically generates a thumbnail registry from assets folder
 */
export function thumbnailRegistryPlugin(options: Partial<ThumbnailRegistryOptions> = {}): Plugin {
	const opts = { ...defaultOptions, ...options };
	
	return {
		name: 'thumbnail-registry',
		async buildStart() {
			await generateThumbnailRegistry(opts);
		},
		async handleHotUpdate({ file }) {
			// Regenerate registry when assets change
			if (file.includes(opts.assetsDir)) {
				await generateThumbnailRegistry(opts);
			}
		}
	};
}

async function generateThumbnailRegistry(options: ThumbnailRegistryOptions): Promise<void> {
	try {
		const thumbnails = await scanAssetsDirectory(options.assetsDir, options.imageExtensions);
		const registryContent = generateRegistryCode(thumbnails);
		
		// Write the generated registry file
		const { writeFile, mkdir } = await import('fs/promises');
		await mkdir(dirname(options.outputFile), { recursive: true });
		await writeFile(options.outputFile, registryContent, 'utf-8');
		
		console.log(`Generated thumbnail registry with ${thumbnails.length} images`);
	} catch (error) {
		console.error('Error generating thumbnail registry:', error);
	}
}

async function scanAssetsDirectory(assetsDir: string, extensions: string[]): Promise<string[]> {
	const thumbnails: string[] = [];
	
	async function scanDir(dir: string): Promise<void> {
		try {
			const items = await readdir(dir);
			
			for (const item of items) {
				const fullPath = join(dir, item);
				const stats = await stat(fullPath);
				
				if (stats.isDirectory()) {
					await scanDir(fullPath);
				} else if (stats.isFile()) {
					const ext = extname(item).toLowerCase();
					if (extensions.includes(ext)) {
						// Get relative path from assets directory
						const relativePath = relative(assetsDir, fullPath).replace(/\\/g, '/');
						thumbnails.push(relativePath);
					}
				}
			}
		} catch (error) {
			console.warn(`Could not scan directory ${dir}:`, error);
		}
	}
	
	await scanDir(assetsDir);
	return thumbnails;
}

function generateRegistryCode(thumbnails: string[]): string {
	const imports = thumbnails.map((thumbnail, index) => {
		const varName = `img_${index}`;
		const varNameEnhanced = `img_${index}_enhanced`;
		
		return {
			plain: `import ${varName} from '../assets/${thumbnail}';`,
			enhanced: `import ${varNameEnhanced} from '../assets/${thumbnail}?enhanced';`,
			varName,
			varNameEnhanced,
			path: thumbnail
		};
	});

	const code = `// This file is auto-generated by the thumbnail-registry Vite plugin
// Do not edit manually - changes will be overwritten

import type { Picture } from 'vite-imagetools';

// Type for thumbnail entries - can be either a Picture object (enhanced) or a string URL (plain)
export type ThumbnailEntry = Picture | string;

// Static imports for all thumbnails
${imports.map(imp => imp.plain).join('\n')}

// Static imports for enhanced thumbnails (with vite-imagetools processing)
${imports.map(imp => imp.enhanced).join('\n')}

/**
 * Auto-generated thumbnail registry
 */
export class GeneratedThumbnailRegistry {
	private static readonly thumbnailMap: Record<string, ThumbnailEntry> = {
${imports.map(imp => `		'${imp.path}': ${imp.varName},\n		'${imp.path}?enhanced': ${imp.varNameEnhanced},`).join('\n')}
	};

	/**
	 * Get a thumbnail by its path.
	 * @param thumbnailPath - The path of the thumbnail as specified in article metadata
	 * @returns The Picture object or string URL, or undefined if not found
	 */
	static getThumbnail(thumbnailPath: string): ThumbnailEntry | undefined {
		const thumbnail = this.thumbnailMap[thumbnailPath];
		
		if (!thumbnail) {
			console.warn(\`Thumbnail not found: \${thumbnailPath}. Available thumbnails:\`, Object.keys(this.thumbnailMap));
		}

		return thumbnail;
	}

	/**
	 * Get all available thumbnail paths.
	 * Useful for debugging and development.
	 */
	static getAvailableThumbnails(): string[] {
		return Object.keys(this.thumbnailMap);
	}

	/**
	 * Check if a thumbnail exists in the registry.
	 */
	static hasThumbnail(thumbnailPath: string): boolean {
		return thumbnailPath in this.thumbnailMap;
	}
}
`;

	return code;
}