// This file is auto-generated by the thumbnail-registry Vite plugin
// Do not edit manually - changes will be overwritten

import type { Picture } from 'vite-imagetools';

// Type for thumbnail entries - can be either a Picture object (enhanced) or a string URL (plain)
export type ThumbnailEntry = Picture | string;

// Static imports for all thumbnails
import img_0 from '../assets/afterlife.webp';
import img_1 from '../assets/crossfit-lsd.webp';
import img_2 from '../assets/favicon.jpg';
import img_3 from '../assets/favicon.svg';
import img_4 from '../assets/lecteur-musique.webp';
import img_5 from '../assets/logo-april-marine.webp';
import img_6 from '../assets/logo.png';
import img_7 from '../assets/logo.webp';
import img_8 from '../assets/ntfy-sveltekit/homepage.png';

// Static imports for enhanced thumbnails (with vite-imagetools processing)
import img_0_enhanced from '../assets/afterlife.webp?enhanced';
import img_1_enhanced from '../assets/crossfit-lsd.webp?enhanced';
import img_2_enhanced from '../assets/favicon.jpg?enhanced';
import img_3_enhanced from '../assets/favicon.svg?enhanced';
import img_4_enhanced from '../assets/lecteur-musique.webp?enhanced';
import img_5_enhanced from '../assets/logo-april-marine.webp?enhanced';
import img_6_enhanced from '../assets/logo.png?enhanced';
import img_7_enhanced from '../assets/logo.webp?enhanced';
import img_8_enhanced from '../assets/ntfy-sveltekit/homepage.png?enhanced';

/**
 * Auto-generated thumbnail registry
 */
export class GeneratedThumbnailRegistry {
	private static readonly thumbnailMap: Record<string, ThumbnailEntry> = {
		'afterlife.webp': img_0,
		'afterlife.webp?enhanced': img_0_enhanced,
		'crossfit-lsd.webp': img_1,
		'crossfit-lsd.webp?enhanced': img_1_enhanced,
		'favicon.jpg': img_2,
		'favicon.jpg?enhanced': img_2_enhanced,
		'favicon.svg': img_3,
		'favicon.svg?enhanced': img_3_enhanced,
		'lecteur-musique.webp': img_4,
		'lecteur-musique.webp?enhanced': img_4_enhanced,
		'logo-april-marine.webp': img_5,
		'logo-april-marine.webp?enhanced': img_5_enhanced,
		'logo.png': img_6,
		'logo.png?enhanced': img_6_enhanced,
		'logo.webp': img_7,
		'logo.webp?enhanced': img_7_enhanced,
		'ntfy-sveltekit/homepage.png': img_8,
		'ntfy-sveltekit/homepage.png?enhanced': img_8_enhanced,
	};

	/**
	 * Get a thumbnail by its path.
	 * @param thumbnailPath - The path of the thumbnail as specified in article metadata
	 * @returns The Picture object or string URL, or undefined if not found
	 */
	static getThumbnail(thumbnailPath: string): ThumbnailEntry | undefined {
		const thumbnail = this.thumbnailMap[thumbnailPath];
		
		if (!thumbnail) {
			console.warn(`Thumbnail not found: ${thumbnailPath}. Available thumbnails:`, Object.keys(this.thumbnailMap));
		}

		return thumbnail;
	}

	/**
	 * Get all available thumbnail paths.
	 * Useful for debugging and development.
	 */
	static getAvailableThumbnails(): string[] {
		return Object.keys(this.thumbnailMap);
	}

	/**
	 * Check if a thumbnail exists in the registry.
	 */
	static hasThumbnail(thumbnailPath: string): boolean {
		return thumbnailPath in this.thumbnailMap;
	}
}
